### ISSUE TITLE
Validations for user sign up and log in

### ISSUE THREAD

**Issue by adriannebulao** [QuicKeys/quickeys#10]
- [ ] Prevent user from completing sign up if passwords don't match https://github.com/QuicKeys/quickeys/blob/92620af94d528636ec7116b85b3c5043dea4e067/frontend/src/components/pages/SignUp.jsx#L33-L47
https://github.com/QuicKeys/quickeys/blob/92620af94d528636ec7116b85b3c5043dea4e067/frontend/src/components/pages/SignUp.jsx#L127-L171

**Comment by markclarde** [comment]
fixed
